version: 2

models:
  - name: stg_telegram_messages
    description: Cleaned Telegram messages
    columns:
      - name: message_id
        tests: [unique, not_null]
      - name: channel_name
        tests: [not_null]
